# Date: Thu, 20 Apr 2023 14:09:26 -0500
on: [push]
jobs:
  connect:
    # macos-latest
    # ubuntu-latest
    # windows-2022
    # windows-2019
    # For more see
    # <https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners>
    #
    # The following works on unix (both ubuntu and mac)
    runs-on: windows-latest
    steps:
        # On windows, this runs on powershell, apparently
      - run: |
            Add-WindowsCapability -Online -Name OpenSSH.Client~~~~0.0.1.0
            bash -c '
            mkdir possibly_second_sshd
            cd possibly_second_sshd
            cat <<EOF >sshd_config
            PermitRootLogin prohibit-password
            AuthorizedKeysFile authorized_keys
            EOF
            cat <<EOF | base64 -d >authorized_keys
            c3NoLWVkMjU1MTkgQUFBQUMzTnphQzFsWkRJMU5URTVBQUFBSUY1dmd5Q2VCUX
            lOR0JpeDliaVpHM1NBRjFoekhNczhGRDI1WXNXS1NmUGIgZnJhbmtzZWlmZmVy
            dGhAcG9zdGVvLm5ldAo=
            EOF
            echo "${{secrets.PRIVATE_KEY}}" >ssh_host_ed25519_key
            '
      - uses: mxschmitt/action-tmate@v3
