# Date: Thu, 20 Apr 2023 14:09:26 -0500
on: [push]
jobs:
  connect:
    # macos-latest
    # ubuntu-latest
    # windows-2022
    # windows-2019
    # For more see
    # <https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners>
    #
    # The following works on unix (both ubuntu and mac)
    runs-on: windows-latest
    steps:
        # On windows, this runs on powershell, apparently
      - run: |
            Add-WindowsCapability -Online -Name OpenSSH.Client~~~~0.0.1.0
            Add-WindowsCapability -Online -Name OpenSSH.Server~~~~0.0.1.0
            cd C:\Windows\System32\OpenSSH
            echo "${{secrets.PRIVATE_KEY}}" >ssh_host_ed25519_key
            bash -c '
            cat <<EOF >possibly_second_sshd_config
            PermitRootLogin prohibit-password
            AuthorizedKeysFile C:\Windows\System32\OpenSSH\authorized_keys
            EOF
            cat <<EOF | base64 -d >authorized_keys
            c3NoLWVkMjU1MTkgQUFBQUMzTnphQzFsWkRJMU5URTVBQUFBSUY1dmd5Q2VCUX
            lOR0JpeDliaVpHM1NBRjFoekhNczhGRDI1WXNXS1NmUGIgZnJhbmtzZWlmZmVy
            dGhAcG9zdGVvLm5ldAo=
            EOF
            '
            sshd -h $PWD/host_id_ed25519 -f $PWD/sshd_config -p 2233
      - uses: mxschmitt/action-tmate@v3
