# Date: Thu, 20 Apr 2023 13:33:16 -0500
on: [push]
jobs:
  connect:
    # macos-latest
    # ubuntu-latest
    # windows-2022
    # windows-2019
    # For more see
    # <https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners>
    #
    # The following works on unix (both ubuntu and mac)
    runs-on: windows-latest
    steps:
      - run: |
            powershell Add-WindowsCapability -Online -Name OpenSSH.Client~~~~0.0.1.0
            md possibly_second_sshd
            chdir possibly_second_sshd
            echo "${{secrets.PRIVATE_KEY}}" >ssh_host_ed25519_key
            > sshd_config (
                @echo.PermitRootLogin prohibit-password
                @echo.AuthorizedKEysFile authorized_keys
            )
            > authorized_keys (
                @echo.ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIF5vgyCeBQyNGBix9biZG3SAF1hzHMs8FD25YsWKSfPb frankseifferth@posteo.net
            )
      - uses: mxschmitt/action-tmate@v3
